# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XmattersSync < Formula
  desc "A CLI script to sync a users schedule from xMatters to a Google Calendar SDK
Usage: `xmatters-sync`
To re-configure: `xmatters-sync --config`
"
  homepage "https://github.com/TomHart/xmatters-sync"
  version "0.3.1"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/TomHart/xmatters-sync/releases/download/v0.3.1/xmatters-sync_Darwin_arm64.tar.gz"
    sha256 "501f01f41c44ef80ca5eda621506e5bbe0f3d0a274afd584c379a2e2ac9c5716"

    def install
      bin.install "xmatters-sync"
    end
  end
end
