# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XmattersSync < Formula
  desc ""
  homepage ""
  version "0.3.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/TomHart/xmatters-sync/releases/download/v0.3.0/xmatters-sync_Darwin_arm64.tar.gz"
    sha256 "eb1cb98b9e2e99e9d4c07710c68e90f81b9b698b710db4a647a105ea71a33d14"

    def install
      bin.install "xmatters-sync"
    end
  end
end
